<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Multinivel I</title>

<script src="site_libs/header-attrs-2.1/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/clipboard-2.0.6/clipboard.min.js"></script>
<link href="site_libs/xaringanExtra-clipboard-0.1.0/xaringanExtra-clipboard.css" rel="stylesheet" />
<script src="site_libs/xaringanExtra-clipboard-0.1.0/xaringanExtra-clipboard.js"></script>
<script>window.xaringanExtraClipboard(null, {"button":"<i class=\"fa fa-clipboard\"><\/i>","success":"<i class=\"fa fa-check\" style=\"color: #90BE6D\"><\/i>","error":"Press Ctrl+C to Copy"})</script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link href="site_libs/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Análisis de Datos Multinivel - SOL3051</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-desktop"></span>
     
    Sesiones
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="00-intro-r.html">Sesión 00</a>
    </li>
    <li>
      <a href="01-multinivel-a.html">Sesión 01</a>
    </li>
  </ul>
</li>
<li>
  <a href="links.html">
    <span class="ion ion-social-markdown"></span>
     
    Links
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Multinivel I</h1>
<h4 class="date">jueves 03 septiembre</h4>

</div>


<p><strong>Libraries</strong></p>
<pre class="r"><code>install.packages(&quot;pacman&quot;) #**ESTO SE DEBE CORRER UNA SOLA VEZ** (!)
pacman::p_load(dplyr, summarytools, ggplot2,ggExtra,lme4,texreg)</code></pre>
<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class="blue">
<p><strong>Descargar:</strong></p>
<ul>
<li><a href="https://jciturras.github.io/ayudantia-sol3051/data/popular2.sav">Datos .sav</a></li>
<li><a href="https://jciturras.github.io/ayudantia-sol3051/rscript/01-multinivel-a.R">Rscript</a></li>
</ul>
</div>
<p><strong>Contenidos ayudantía</strong></p>
<ol style="list-style-type: decimal">
<li>Modelo Nulo y Correlación Intraclase</li>
<li>Varianza within/between</li>
<li>Modelos con intercepto aleatorio</li>
<li>Modelos con intercepto y pendiente aleatoria</li>
<li>Interacciones:
<ol style="list-style-type: upper-alpha">
<li>Nivel individual</li>
<li>Nivel cruzado</li>
</ol></li>
</ol>
<p><strong>Datos</strong></p>
<p>Los datos de popularidad en <code>popular</code> son datos simulados para 2000 alumnos en 100 escuelas. El propósito es ofrecer un ejemplo muy simple para el análisis de regresión multinivel. La principal variable dependiente es la popularidad del alumno, medida a través un índice de popularidad en una escala del 1 al 10 a través de un procedimiento sociométrico.</p>
<p>Por lo general, un procedimiento sociométrico pide a todos los alumnos de una clase que califiquen a todos los demás alumnos y luego asigna a cada alumno el índice de popularidad promedio recibido.</p>
<ul>
<li><p>Debido al procedimiento sociométrico, los efectos de grupo como son evidentes en los componentes de varianza de nivel superior son bastante fuertes.</p></li>
<li><p>Hay una segunda variable de resultado: la popularidad del alumno según la calificación de su maestro, en una escala del 1 al 10.</p></li>
<li><p>Las variables explicativas son el sexo del alumno (hombre = 0, mujer = 1), la extraversión del alumno (escala de 10 puntos) y la experiencia del profesor en años.</p></li>
</ul>
<p><strong>Cargar Datos</strong></p>
<pre class="r"><code>popdata &lt;- read_spss(&quot;data/popular2.sav&quot;)</code></pre>
<pre class="r"><code>popdata &lt;- read_spss(&quot;https://jciturras.github.io/ayudantia-sol3051/data/popular2.sav&quot;)</code></pre>
<p><strong>Seleccionar variables</strong></p>
<pre class="r"><code>popdata&lt;- popdata %&gt;% select(pupil,class,popular,sex,extrav,texp)</code></pre>
<p><strong>Descriptivos</strong>
<div class="container st-container">
<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline ">
  <thead>
    <tr>
      <th align="center" class="st-protect-top-border"><strong>No</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Variable</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Label</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Stats / Values</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Freqs (% of Valid)</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Graph</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Valid</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Missing</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center">1</td>
      <td align="left">pupil
[numeric]</td>
      <td align="left">pupil ident</td>
      <td align="left">Mean (sd) : 10.6 (6)
min < med < max:
1 < 11 < 26
IQR (CV) : 10 (0.6)</td>
      <td align="left" style="vertical-align:middle">26 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqby8vL///8shn5hAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AkDEg0jVs9GigAAAIlJREFUaN7t2csNgCAQANFtgRLEDqD/3tSFGEIwmoWDgZkTq+HFgwc/ImTJa+7KP+deytgez4Lu0GWa470szn/F6s2tOYDNhOn9sQ3C9CAYGBgY2LpY+0HGiKUZDAwMDAwMDAwMDGw9rH6z6MLqywMDAwMDA/sJVvyg6cd0BpsJS59aM+aHJGTpAOW0h8vScr2ZAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIwLTA5LTAzVDIyOjEzOjM1LTA0OjAw1RAG9gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMC0wOS0wM1QyMjoxMzozNS0wNDowMKRNvkoAAAAASUVORK5CYII="></td>
      <td align="center">2000
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">2</td>
      <td align="left">class
[numeric]</td>
      <td align="left">class ident</td>
      <td align="left">Mean (sd) : 50.4 (29.1)
min < med < max:
1 < 51 < 100
IQR (CV) : 51 (0.6)</td>
      <td align="left" style="vertical-align:middle">100 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqby8vL///8shn5hAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AkDEg0jVs9GigAAAIVJREFUaN7t0MENgDAIhWFW0A3EDer+u5lYeiAhtcXe/N+FlIQPUhGSyZbLrjX2NMyaxyx2PSkeO2t3KTZ7YBd7P9D/0ggWHdgUNz6CRQe2uRCzRWswKz1MXT5irhQ/F27IYmEBAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA/sFpksiJJMblJQ4c81MDdEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjAtMDktMDNUMjI6MTM6MzUtMDQ6MDDVEAb2AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIwLTA5LTAzVDIyOjEzOjM1LTA0OjAwpE2+SgAAAABJRU5ErkJggg=="></td>
      <td align="center">2000
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">3</td>
      <td align="left">popular
[numeric]</td>
      <td align="left">popularity sociometric score</td>
      <td align="left">Mean (sd) : 5.1 (1.4)
min < med < max:
0 < 5.1 < 9.5
IQR (CV) : 1.9 (0.3)</td>
      <td align="left" style="vertical-align:middle">85 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqby8vL///8shn5hAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AkDEg0jVs9GigAAAIdJREFUaN7t18ENgCAMQFFW0BFwA9l/NxPLpUlTscWD+v8ZXnoitBSKtFy2Vsk7M461sz2J9ZHmYJsoYGBgYGBgYGBgYLcw75/sYf2exrwBPUyUBgYGBgYGBgYGBgb2XszcLaKYOeDzmNpzsphSwMDAPoZZz0UYsxQX0w9uEtMD/gurUyoU6QBrpjDZx3J6zQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wOS0wM1QyMjoxMzozNS0wNDowMNUQBvYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDktMDNUMjI6MTM6MzUtMDQ6MDCkTb5KAAAAAElFTkSuQmCC"></td>
      <td align="center">2000
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">4</td>
      <td align="left">sex
[numeric]</td>
      <td align="left">pupil sex</td>
      <td align="left">Min : 0
Mean : 0.5
Max : 1</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">0</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">989</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">49.5%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">1</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">1011</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">50.5%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFgAAAA4BAMAAACLTyJdAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AkDEg0jVs9GigAAADxJREFUSMdjYBiaQIkYoAhVrGxMBBhVPKp4VDHNFJOUYQWJAoNLMVEeVCIl6IxGFY8qHlVMK8UkZdihBgAUZEkqMlG4MQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wOS0wM1QyMjoxMzozNS0wNDowMNUQBvYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDktMDNUMjI6MTM6MzUtMDQ6MDCkTb5KAAAAAElFTkSuQmCC"></td>
      <td align="center">2000
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">5</td>
      <td align="left">extrav
[numeric]</td>
      <td align="left">extraversion</td>
      <td align="left">Mean (sd) : 5.2 (1.3)
min < med < max:
1 < 5 < 10
IQR (CV) : 2 (0.2)</td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">1</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">3</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.1%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">2</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">13</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.6%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">3</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">119</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">5.9%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">4</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">423</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">21.1%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">5</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">688</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">34.4%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">6</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">478</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">23.9%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">7</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">194</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">9.7%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">8</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">58</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">2.9%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">9</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">18</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.9%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 0 0 7px;margin:0;border:0" align="right">10</td><td style="padding:0 2px;border:0;" align="left">:</td><td style="padding:0 4px 0 6px;margin:0;border:0" align="right">6</td><td style="padding:0;border:0" align="left">(</td><td style="padding:0 2px;margin:0;border:0" align="right">0.3%</td><td style="padding:0 4px 0 0;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEAAAAD6BAMAAADjFlz+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqb39/f///+DdZCQAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AkDEg0jVs9GigAAAJhJREFUaN7t08EJgDAMRmFXyAixG9j9d1NPVjANiIktvHf+Di3kX5YxUrECAAYFMgBYAYDZgMSD9awHSq11AwDygHuTYpY8nKbHbzZtAEAwcG/yh11cPf+i+Q8AEALcm0zYxYvhaHf+RwBAKHBvMm8XaoJyfzoAEA3cmxSzzOFoH5QKAKQC9ybF7LtdAACzARkAKAAwG/i7HcIhaISH3JCmAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIwLTA5LTAzVDIyOjEzOjM1LTA0OjAw1RAG9gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMC0wOS0wM1QyMjoxMzozNS0wNDowMKRNvkoAAAAASUVORK5CYII="></td>
      <td align="center">2000
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
    <tr>
      <td align="center">6</td>
      <td align="left">texp
[numeric]</td>
      <td align="left">teacher experience in years</td>
      <td align="left">Mean (sd) : 14.3 (6.6)
min < med < max:
2 < 15 < 25
IQR (CV) : 12 (0.5)</td>
      <td align="left" style="vertical-align:middle">24 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent"><img style="border:none;background-color:transparent;padding:0" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqby8vL///8shn5hAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5AkDEg0jVs9GigAAAKlJREFUaN7t1l0KgCAQRlG3UDtId1D731ukhANWijP0x/0eehjlBMY4OUd6MlQz+pjLPe3YsmUGAwMDAwN7NZZm32SDhVi5ETsZ3Z3Y8UmDgYE1YuI60WNi4eziMsLi4gz2AJa+oxGWygU25ncYYLkMVsdEn+ox8Xw7Jv9M1FgQjfFBTLSfHiv2/weTM02Nhav9YPvNZISlMhgYGBgYGBgY2P8xbxJHerICxqvrTOp0WfwAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjAtMDktMDNUMjI6MTM6MzUtMDQ6MDDVEAb2AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIwLTA5LTAzVDIyOjEzOjM1LTA0OjAwpE2+SgAAAABJRU5ErkJggg=="></td>
      <td align="center">2000
(100%)</td>
      <td align="center">0
(0%)</td>
    </tr>
  </tbody>
</table>
<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 0.9.6 (<a href='https://www.r-project.org/'>R</a> version 4.0.2)<br/>2020-09-03</p>
</div></p>
<div id="práctica" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Práctica</h1>
<div id="varianza-withinbetween" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Varianza within/between</h2>
<div class="figure">
<img src="https://www.researchgate.net/profile/Gabriel_Liguori/publication/329788831/figure/fig2/AS:711397558206464@1546621803288/Graphical-representation-of-the-rationale-behind-the-analysis-of-variance-ANOVA-A.png" alt="" />
<p class="caption">Varianza within y between</p>
</div>
<ul>
<li><p>En el caso A, vemos que al interior de los grupos la varianza es <strong>alta</strong>, pero la varianza entre grupos es <strong>baja</strong>.</p></li>
<li><p>En el caso B, vemos que al interior de los grupos la varianza es <strong>baja</strong>, pero la varianza entre grupos es <strong>alta</strong>.</p></li>
</ul>
<p>Ahora, ejemplifiquemos con nuestros datos. Seleccionamos tres cursos para observar cómo se distribuye la popularidad de los alumnos al interior de cada uno y a la vez, es posible identificar la variacion entre cursos. En este caso <strong>La media de popularidad en la muestra es de 5.07645.</strong></p>
<pre class="r"><code>popdata %&gt;% 
  filter(class %in% c(82,74,33)) %&gt;%
  group_by(class) %&gt;% 
  summarise(mean_j=mean(popular),var_j=var(popular),sd_j=sd(popular)) %&gt;% data.frame()</code></pre>
<pre><code>##   class   mean_j     var_j      sd_j
## 1    33 7.326316 1.8042690 1.3432308
## 2    74 5.076471 0.9994118 0.9997058
## 3    82 2.595238 1.5774762 1.2559762</code></pre>
<pre class="r"><code>popdata %&gt;% filter(class %in% c(82,74,33)) %&gt;% 
  ggplot() + 
  geom_density(aes(x = popular,fill=factor(class,levels = c(82,74,33))),alpha=0.3) +
  geom_vline(xintercept = mean(popdata$popular),color=&quot;red&quot;,linetype=&quot;dashed&quot;, size=1) +
  ylab(&quot;Densidad&quot;)+
  xlab(&quot;Popularidad alumno&quot;) +
  scale_fill_discrete(&quot;ID Curso&quot;)+
  theme_classic()+ 
  theme(legend.position = &quot;top&quot;)</code></pre>
<p><img src="01-multinivel-a_files/figure-html/unnamed-chunk-10-1.png" width="1152" /></p>
<ul>
<li>Por un lado vemos que el curso 33 es la que posee un promedio más alto, siguiendo la curso 74 y luego 82 Por otro lado, vemos que el curso 2 es aquella que posee menor variación al interior, e contraste de la escuela 1 y 11.</li>
</ul>
<p><strong>Ahora, veamos la variación entre escuelas (between):</strong></p>
<pre class="r"><code>popdata &lt;- popdata %&gt;%  mutate(mean_i=mean(popular))  # media muestral
popdata &lt;- popdata %&gt;%  group_by(class) %&gt;% mutate(mean_j=mean(popular)) # media para grupos</code></pre>
<pre class="r"><code>p&lt;- popdata %&gt;% 
  ggplot() +
  geom_point(aes(y = mean_j,x = class)) +
  geom_hline(yintercept = 5.03,color=&quot;red&quot;) +
  ylab(&quot;Media popularidad (Curso)&quot;)+
  xlab(&quot;ID Curso&quot;)+
  theme_classic() + 
  geom_text(data=subset(popdata, class %in%c(82,74,33)),
            aes(y = mean_j,x = class,label=class),
            nudge_x = -1,
            nudge_y = -0.1, 
            color=&quot;blue&quot;)
ggMarginal(p, type=&quot;box&quot;,margins = &#39;y&#39;,fill = &#39;#00A2FF81&#39;, size=20) </code></pre>
<p><img src="01-multinivel-a_files/figure-html/unnamed-chunk-12-1.png" width="1152" /></p>
<p>En este gráfico se puede observar la variación de los promedios de popularidad por curso, donde la línea roja horizontal representa la media total de la muestra, es decir, la media para todos los alumnos de todos los cursos.</p>
</div>
<div id="modelo-nulo" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Modelo nulo</h2>
<p>El “modelo nulo” refiere al modelo que no considera ningún predictor, pero sí considera la estructura anidada de los datos.</p>
<pre class="r"><code>m00&lt;-lmer(popular ~ (1|class), popdata)
summary(m00)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: popular ~ (1 | class)
##    Data: popdata
## 
## REML criterion at convergence: 6330.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5655 -0.6975  0.0020  0.6758  3.3175 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  class    (Intercept) 0.7021   0.8379  
##  Residual             1.2218   1.1053  
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  5.07786    0.08739    58.1</code></pre>
<p>En el output vemos dos parte centrales:</p>
<ol style="list-style-type: decimal">
<li><p><strong><code>Random effects</code> (parte ‘aleatoria’):</strong> Nos muestra la variabilidad correspondiente a nivel ‘intra’ o individual (within) y a nivel ‘entre’ grupal (between).</p></li>
<li><p><strong><code>Fixed effects</code> (parte ‘fija’):</strong> Muestra los valores del intercepto y los coeficientes o pendientes (slopes) . Para referirse a estos términos se habla de ‘efectos fijos’ en referencia a los parámetros del modelo como en un modelo de regresión tradicional.</p></li>
</ol>
<p>En base a esta información podemos calcular la correlación intra-clase (ICC por Intraclass correlation). Medida que representa la proporción de la varianza de popularidad que es explicada por la pertenencia a unidades de nivel 2, que en este caso son los cursos. Para ello, utilizamos la información contenida en <code>Random effects</code>.</p>
<pre class="r"><code>sigma2_mu &lt;- VarCorr(m00)$class[[1]]
sigma2_e &lt;- sigma(m00)^2</code></pre>
<p>Tenemo que la correlación intraclase se calcula con:</p>
<p><span class="math inline">\(\rho = \frac{\sigma_{\mu_0}^2}{\sigma_{\mu_0}^2+\sigma_{\epsilon}^2} = \frac{0.702}{0.702+1.221}=\)</span></p>
<pre class="r"><code>sigma2_mu / (sigma2_mu+sigma2_e)</code></pre>
<pre><code>## [1] 0.3649386</code></pre>
<p><span class="math inline">\(\rho\)</span> = 0.365</p>
<p><strong>Interpretación</strong></p>
<p>La correlación intraclase nos indica que una proporción del <strong>0.365</strong> de la variable popularidad que es atribuible a la pertenencia a unidades de nivel 2. En este caso, sería la proporción atribuible a la varianza entre-escuelas (between)</p>
<p><strong>Visualización de efectos aleatorios</strong></p>
<pre class="r"><code>library(lattice)
qqmath(ranef(m00, condVar = TRUE))</code></pre>
<pre><code>## $class</code></pre>
<p><img src="01-multinivel-a_files/figure-html/unnamed-chunk-16-1.png" width="1152" /></p>
</div>
<div id="modelo-con-intercepto-aleatorio" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Modelo con intercepto aleatorio</h2>
<p>A diferencia del modelo nulo, el modelo con intercepto aleatorio considera predictores en la estimación. Para este caso, utilizamos sexo (mujer=1), extraversión del alumno y la experiencia del profesor.</p>
<pre class="r"><code>m01.ri&lt;- lmer(popular ~ sex + extrav + texp + (1 |class), popdata)
screenreg(list(m00,m01.ri), custom.model.names = c(&quot;Modelo Nulo&quot;, &quot;Modelo 1&quot;))</code></pre>
<pre><code>## 
## ==================================================
##                         Modelo Nulo   Modelo 1    
## --------------------------------------------------
## (Intercept)                 5.08 ***      0.81 ***
##                            (0.09)        (0.17)   
## sex                                       1.25 ***
##                                          (0.04)   
## extrav                                    0.45 ***
##                                          (0.02)   
## texp                                      0.09 ***
##                                          (0.01)   
## --------------------------------------------------
## AIC                      6336.51       4897.02    
## BIC                      6353.31       4930.63    
## Log Likelihood          -3165.25      -2442.51    
## Num. obs.                2000          2000       
## Num. groups: class        100           100       
## Var: class (Intercept)      0.70          0.30    
## Var: Residual               1.22          0.59    
## ==================================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p><strong>Interpretación</strong></p>
<p>En el caso del Modelo Nulo</p>
<p>El intercepto para un modelo sin predictores representa el promedio de popularidad entre todos los cursos y estudiantes, que en este caso es 5.08.</p>
<p>La varianza de los residuos a nivel de alumno es representada se puede ver en <code>Var: Residual</code> con un valor de 1.22, mientras que la varianza del residuo a nivel del curso se puede observar en <code>Var: class (Intercept)</code> con un valor de 0.7.</p>
<p>En el Modelo 1 es el modelo con intercepto aleatorio y pendendientes fijas. Es decir, sólo el intercepto varía entre cursos, mientras que los efectos de sexo y extraversión se <strong>consideran fijos</strong> (no varían según curso).</p>
</div>
<div id="modelo-con-intercepto-y-pendiente-aleatoria" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Modelo con intercepto y pendiente aleatoria</h2>
<pre class="r"><code>m01.rirs&lt;- lmer(popular ~ sex + extrav + texp + (1+ sex + extrav |class), popdata)
screenreg(list(m01.ri,m01.rirs),custom.model.names = c(&quot;Modelo 1&quot;, &quot;Modelo 2&quot;))</code></pre>
<pre><code>## 
## =========================================================
##                                Modelo 1      Modelo 2    
## ---------------------------------------------------------
## (Intercept)                        0.81 ***      0.76 ***
##                                   (0.17)        (0.20)   
## sex                                1.25 ***      1.25 ***
##                                   (0.04)        (0.04)   
## extrav                             0.45 ***      0.45 ***
##                                   (0.02)        (0.02)   
## texp                               0.09 ***      0.09 ***
##                                   (0.01)        (0.01)   
## ---------------------------------------------------------
## AIC                             4897.02       4855.26    
## BIC                             4930.63       4916.87    
## Log Likelihood                 -2442.51      -2416.63    
## Num. obs.                       2000          2000       
## Num. groups: class               100           100       
## Var: class (Intercept)             0.30          1.34    
## Var: Residual                      0.59          0.55    
## Var: class sex                                   0.00    
## Var: class extrav                                0.03    
## Cov: class (Intercept) sex                      -0.02    
## Cov: class (Intercept) extrav                   -0.19    
## Cov: class sex extrav                           -0.00    
## =========================================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p><strong>Interpretación</strong></p>
<p>A diferencia del Modelo 1 (Intercepto aleatorio, pendiente fija) el Modelo 2 considera que tanto el sexo como la extraversión de los alumnos tienen una pendiente aleatoria, esto significa que ahora sí se considera que el efecto de ambas variables es distinto según curso. A continuación se puede visualizar el Intercepto para cada curso, como también la pendiente de sexo y extraversión.</p>
<p>Vemos que los coeficientes de todas las variables son estadísticamente significativos al 99.9% de confianza.</p>
<ul>
<li><p>El coeficiente para el género del alumno es 1.24. Dado que el valor 1= mujer y 0= hombre, esto significa que el promedio, las mujeres tienen 1.25 puntos más que los hombres en la escala de popularidad.</p></li>
<li><p>El coeficiente de la extraversión es 0.45, lo cual significa que por cada incremento de una unidad en la escala de estraversión, se espera que la popularidad incremente en 0.45.</p></li>
<li><p>El coeficiente para la experiencia del profesor es de 0.09, lo cual indica que por cada año de experiencia del profesor, la popularidad promedio del curso se incrementa en 0.09 puntos en la escala de popularidad.</p></li>
</ul>
<p>Para visualizarlo, usamos la función <code>lattice::qqmath()</code> sobre <code>lmer::ranef()</code>, esta última función nos entrega los valores de intercepto y pendiente aleatoria para cada curso.</p>
<pre class="r"><code>qqmath(ranef(m01.rirs))</code></pre>
<p><img src="01-multinivel-a_files/figure-html/unnamed-chunk-19-1.png" width="1152" /></p>
<pre><code>## $class</code></pre>
</div>
<div id="interacciones" class="section level2" number="1.5">
<h2><span class="header-section-number">1.5</span> Interacciones</h2>
<ol style="list-style-type: upper-alpha">
<li><strong>Nivel individual:</strong> extraversión <span class="math inline">\(\times\)</span> sexo</li>
</ol>
<p>Este modelo evalúa si el efecto de extraversión está moderado por el sexo del alumno. Para ello, se debe tomar en cuenta que efecto de extraversión varía en magnitud según el curso.</p>
<pre class="r"><code>m02.rirs&lt;- lmer(popular ~  extrav*sex + texp + (1+ sex + extrav |class), popdata)</code></pre>
<ol start="2" style="list-style-type: upper-alpha">
<li><strong>Nivel cruzado:</strong> extraversión <span class="math inline">\(\times\)</span> experiencia profesor</li>
</ol>
<p>En este ejemplo veremos si la experiencia del profesor modera el efecto de extraversión sobre popularidad.</p>
<pre class="r"><code>m03.rirs&lt;- lmer(popular ~ sex + extrav*texp + (1+ sex + extrav |class), popdata)</code></pre>
<pre class="r"><code>screenreg(list(m01.rirs,m02.rirs,m03.rirs))</code></pre>
<pre><code>## 
## =======================================================================
##                                Model 1       Model 2       Model 3     
## -----------------------------------------------------------------------
## (Intercept)                        0.76 ***      0.91 ***     -1.21 ***
##                                   (0.20)        (0.21)        (0.27)   
## sex                                1.25 ***      0.97 ***      1.24 ***
##                                   (0.04)        (0.16)        (0.04)   
## extrav                             0.45 ***      0.42 ***      0.80 ***
##                                   (0.02)        (0.03)        (0.04)   
## texp                               0.09 ***      0.09 ***      0.23 ***
##                                   (0.01)        (0.01)        (0.02)   
## extrav:sex                                       0.05                  
##                                                 (0.03)                 
## extrav:texp                                                   -0.02 ***
##                                                               (0.00)   
## -----------------------------------------------------------------------
## AIC                             4855.26       4859.45       4802.34    
## BIC                             4916.87       4926.66       4869.55    
## Log Likelihood                 -2416.63      -2417.72      -2389.17    
## Num. obs.                       2000          2000          2000       
## Num. groups: class               100           100           100       
## Var: class (Intercept)             1.34          1.40          0.49    
## Var: class sex                     0.00          0.00          0.00    
## Var: class extrav                  0.03          0.04          0.01    
## Cov: class (Intercept) sex        -0.02         -0.01         -0.02    
## Cov: class (Intercept) extrav     -0.19         -0.20         -0.03    
## Cov: class sex extrav             -0.00         -0.00         -0.00    
## Var: Residual                      0.55          0.55          0.55    
## =======================================================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p><strong>Interpretación</strong></p>
<ol style="list-style-type: upper-alpha">
<li>El coeficiente de extraversión (<code>extrav</code>) es de 0.42 y el coeficiente multiplicativo de extrav:sex es de 0.05. Sin embargo, el coeficiente multiplicativo no es estadísticamente signficativo.</li>
</ol>
<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class="blue">
<p>Lo que nos indica es que el efecto de extraversión varía positivamente según el sexo del alumno. En este caso, dado que sexo=1 corresponde a las mujeres, vemos que en la medida que aumenta la extraversión del alumno, las mujeres sostenidamente tendrán un efecto mayor al de los hombres. Manteniendo todas las demás variables constantes.</p>
</div>
<ol start="2" style="list-style-type: upper-alpha">
<li>El coeficiente de extraversión (<code>extrav</code>) es de 0.80 y el coeficiente multiplicativo de extrav:texp es de -0.02, los cual es pequeño pero estadísticamente significativo al 99.9% de confianza.</li>
</ol>
<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class="blue">
<p>El valor negativo del del coeficiente multiplicativo de nivel cruzado nos indica que cuando los profesores son experimentados, las ventajas de ser extrovertido son menores de lo que indica el efecto principal de extraversión (0.80). Entonces, la diferencia en popularidad entre alumnos extrovertidos e introvertidos se vuelve menor con profesores más experimentados.</p>
</div>
</div>
</div>

&nbsp;
<hr />
<p style="text-align: center;">Sitio por <a href="https://github.com/jciturras/">Julio Iturra Sanhueza</a></p>
<p style="text-align: center;"><span style="color: #808080;">julioiturrasanhueza@gmail.com</span></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://twitter.com/jciturras" class="fa fa-twitter"></a>
    <a href="https://www.linkedin.com/in/jciturras/" class="fa fa-linkedin"></a>
    <a href="https://github.com/jciturras/" class="fa fa-github"></a>
</p>

&nbsp;


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
